#	"$Name:  $";
#	"$Header:  $";
#=============================================================================
#
# file :        FestivalDS.py
#
# description : Python source for the FestivalDS and its commands. 
#                The class is derived from Device. It represents the
#                CORBA servant object which will be accessed from the
#                network. All commands which can be executed on the
#                FestivalDS are implemented in this file.
#
# project :     TANGO Device Server
#
# $Author:  $
#
# $Revision:  $
#
# $Log:  $
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#  		This file is generated by POGO
#	(Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#


import PyTango
import sys
import os
import time
import threading
import fandango

#==================================================================
#   FestivalDS Class Description:
#
#
#=================================================================

def trace(msg):
  print '%s: %s' % (fandango.time2str(),msg)

def os_cmd(cmd,term=True):
    trace( 'os:> %s'%cmd)
    if term and not cmd.endswith('&'): cmd+=' &'
    os.system(cmd)

def Sequence(i,path,text):
    trace( 'In Sequence Thread ...')
    ev = threading.Event()
    for i in xrange(i):
        os_cmd("padsp play %s" % path,term=False)
        ev.wait(0.5)
    out = 'echo "%s" | padsp festival --tts' % text
    os_cmd(out,term=False)

class FestivalDS(PyTango.Device_4Impl):

#--------- Add you global variables here --------------------------

#------------------------------------------------------------------
#	Device constructor
#------------------------------------------------------------------
    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        FestivalDS.init_device(self)

#------------------------------------------------------------------
#	Device destructor
#------------------------------------------------------------------
    def delete_device(self):
        trace("[Device delete_device method] for device"+self.get_name())
        if self.thread and self.thread.is_alive(): self.thread.join(10.)


#------------------------------------------------------------------
#	Device initialization
#------------------------------------------------------------------
    def init_device(self):
        trace("In "+ self.get_name()+ "::init_device()")
        self.thread = None
        self.set_state(PyTango.DevState.ON)
        self.get_device_properties(self.get_device_class())
        

#------------------------------------------------------------------
#	Always excuted hook method
#------------------------------------------------------------------
    def always_executed_hook(self):
        trace("In "+ self.get_name()+ "::always_excuted_hook()")

#==================================================================
#
#	FestivalDS read/write attribute methods
#
#==================================================================
#------------------------------------------------------------------
#	Read Attribute Hardware
#------------------------------------------------------------------
    def read_attr_hardware(self,data):
        trace("In "+ self.get_name()+ "::read_attr_hardware()")

    ### Commands ###
    def Play(self,text):
        trace( 'In %s.Play(%s)'%(self.get_name(),text))
        out = 'echo "%s" | padsp festival --tts &' % text
        os_cmd(out)

    def Beep(self):
        trace( 'In %s.Beep()'%self.get_name())
        if not self.Beep_Path:
            raise Exception('Wav file not set')
        os_cmd("padsp play %s &" % self.Beep_Path)
        
     
    def Play_Sequence(self, cmd):
        trace( 'In %s.Play_Sequence(%s)'%(self.get_name(),cmd))
        self.thread = threading.Thread(target=Sequence, args=(self.Default_Repeat_Times,self.Beep_Path,cmd))
        self.thread.start()        



#==================================================================
#
#	FestivalDS command methods
#
#==================================================================

#==================================================================
#
#	FestivalDSClass class definition
#
#==================================================================
class FestivalDSClass(PyTango.DeviceClass):

	#	Class Properties
    class_property_list = {
        }


    #	Device Properties
    device_property_list = {
        'Beep_Path':
            [PyTango.DevString,
            "",
            None ],
        'Default_Repeat_Times':
            [PyTango.DevShort,
            "",
            None ],
        #'Default_Text':
            #[PyTango.DevString,
            #"",
            #None ],
        }
		



	#	Command definitions
    cmd_list = {    
    'Play' : 
            [[PyTango.DevString, "Play a given Text"], 
            [PyTango.DevVoid, ""]], 
    'Beep' : 
            [[PyTango.DevVoid, "Force a Beep Sound "], 
            [PyTango.DevVoid, ""]], 
    'Play_Sequence' : 
            [[PyTango.DevString, "Force a Beep Sound with a given speech"], 
            [PyTango.DevVoid, ""]], 
        }


	#	Attribute definitions
    attr_list = {
        }


#------------------------------------------------------------------
#	FestivalDSClass Constructor
#------------------------------------------------------------------
    def __init__(self, name):
        PyTango.DeviceClass.__init__(self, name)
        self.set_type(name);
        print "In FestivalDSClass  constructor"

#==================================================================
#
#	FestivalDS class main method
#
#==================================================================
if __name__ == '__main__':
    try:
        py = PyTango.Util(sys.argv)
        py.add_TgClass(FestivalDSClass,FestivalDS,'FestivalDS')

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e
